// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bank.proto

package org.example.stub;

public final class Bank {
  private Bank() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConvertCurrentRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConvertCurrentRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    java.lang.String getCurrentFrom();
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    com.google.protobuf.ByteString
        getCurrentFromBytes();

    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    java.lang.String getCurrentTo();
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    com.google.protobuf.ByteString
        getCurrentToBytes();

    /**
     * <code>double amout = 3;</code>
     * @return The amout.
     */
    double getAmout();
  }
  /**
   * Protobuf type {@code ConvertCurrentRequest}
   */
  public  static final class ConvertCurrentRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConvertCurrentRequest)
      ConvertCurrentRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertCurrentRequest.newBuilder() to construct.
    private ConvertCurrentRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertCurrentRequest() {
      currentFrom_ = "";
      currentTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertCurrentRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConvertCurrentRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currentFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currentTo_ = s;
              break;
            }
            case 25: {

              amout_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.stub.Bank.internal_static_ConvertCurrentRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.stub.Bank.internal_static_ConvertCurrentRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.stub.Bank.ConvertCurrentRequest.class, org.example.stub.Bank.ConvertCurrentRequest.Builder.class);
    }

    public static final int CURRENTFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentFrom_;
    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    public java.lang.String getCurrentFrom() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    public com.google.protobuf.ByteString
        getCurrentFromBytes() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currentTo_;
    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    public java.lang.String getCurrentTo() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    public com.google.protobuf.ByteString
        getCurrentToBytes() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUT_FIELD_NUMBER = 3;
    private double amout_;
    /**
     * <code>double amout = 3;</code>
     * @return The amout.
     */
    public double getAmout() {
      return amout_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrentFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currentTo_);
      }
      if (amout_ != 0D) {
        output.writeDouble(3, amout_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrentFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currentTo_);
      }
      if (amout_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amout_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.stub.Bank.ConvertCurrentRequest)) {
        return super.equals(obj);
      }
      org.example.stub.Bank.ConvertCurrentRequest other = (org.example.stub.Bank.ConvertCurrentRequest) obj;

      if (!getCurrentFrom()
          .equals(other.getCurrentFrom())) return false;
      if (!getCurrentTo()
          .equals(other.getCurrentTo())) return false;
      if (java.lang.Double.doubleToLongBits(getAmout())
          != java.lang.Double.doubleToLongBits(
              other.getAmout())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentFrom().hashCode();
      hash = (37 * hash) + CURRENTTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTo().hashCode();
      hash = (37 * hash) + AMOUT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmout()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stub.Bank.ConvertCurrentRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.stub.Bank.ConvertCurrentRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConvertCurrentRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConvertCurrentRequest)
        org.example.stub.Bank.ConvertCurrentRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.stub.Bank.internal_static_ConvertCurrentRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.stub.Bank.internal_static_ConvertCurrentRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.stub.Bank.ConvertCurrentRequest.class, org.example.stub.Bank.ConvertCurrentRequest.Builder.class);
      }

      // Construct using org.example.stub.Bank.ConvertCurrentRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentFrom_ = "";

        currentTo_ = "";

        amout_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.stub.Bank.internal_static_ConvertCurrentRequest_descriptor;
      }

      @java.lang.Override
      public org.example.stub.Bank.ConvertCurrentRequest getDefaultInstanceForType() {
        return org.example.stub.Bank.ConvertCurrentRequest.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.stub.Bank.ConvertCurrentRequest build() {
        org.example.stub.Bank.ConvertCurrentRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.stub.Bank.ConvertCurrentRequest buildPartial() {
        org.example.stub.Bank.ConvertCurrentRequest result = new org.example.stub.Bank.ConvertCurrentRequest(this);
        result.currentFrom_ = currentFrom_;
        result.currentTo_ = currentTo_;
        result.amout_ = amout_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.stub.Bank.ConvertCurrentRequest) {
          return mergeFrom((org.example.stub.Bank.ConvertCurrentRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.stub.Bank.ConvertCurrentRequest other) {
        if (other == org.example.stub.Bank.ConvertCurrentRequest.getDefaultInstance()) return this;
        if (!other.getCurrentFrom().isEmpty()) {
          currentFrom_ = other.currentFrom_;
          onChanged();
        }
        if (!other.getCurrentTo().isEmpty()) {
          currentTo_ = other.currentTo_;
          onChanged();
        }
        if (other.getAmout() != 0D) {
          setAmout(other.getAmout());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.stub.Bank.ConvertCurrentRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.stub.Bank.ConvertCurrentRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currentFrom_ = "";
      /**
       * <code>string currentFrom = 1;</code>
       * @return The currentFrom.
       */
      public java.lang.String getCurrentFrom() {
        java.lang.Object ref = currentFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return The bytes for currentFrom.
       */
      public com.google.protobuf.ByteString
          getCurrentFromBytes() {
        java.lang.Object ref = currentFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentFrom() {
        
        currentFrom_ = getDefaultInstance().getCurrentFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The bytes for currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currentTo_ = "";
      /**
       * <code>string currentTo = 2;</code>
       * @return The currentTo.
       */
      public java.lang.String getCurrentTo() {
        java.lang.Object ref = currentTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return The bytes for currentTo.
       */
      public com.google.protobuf.ByteString
          getCurrentToBytes() {
        java.lang.Object ref = currentTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTo() {
        
        currentTo_ = getDefaultInstance().getCurrentTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The bytes for currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentTo_ = value;
        onChanged();
        return this;
      }

      private double amout_ ;
      /**
       * <code>double amout = 3;</code>
       * @return The amout.
       */
      public double getAmout() {
        return amout_;
      }
      /**
       * <code>double amout = 3;</code>
       * @param value The amout to set.
       * @return This builder for chaining.
       */
      public Builder setAmout(double value) {
        
        amout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amout = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmout() {
        
        amout_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConvertCurrentRequest)
    }

    // @@protoc_insertion_point(class_scope:ConvertCurrentRequest)
    private static final org.example.stub.Bank.ConvertCurrentRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.stub.Bank.ConvertCurrentRequest();
    }

    public static org.example.stub.Bank.ConvertCurrentRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertCurrentRequest>
        PARSER = new com.google.protobuf.AbstractParser<ConvertCurrentRequest>() {
      @java.lang.Override
      public ConvertCurrentRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConvertCurrentRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConvertCurrentRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConvertCurrentRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.stub.Bank.ConvertCurrentRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConvertCurrentResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ConvertCurrentResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    java.lang.String getCurrentFrom();
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    com.google.protobuf.ByteString
        getCurrentFromBytes();

    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    java.lang.String getCurrentTo();
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    com.google.protobuf.ByteString
        getCurrentToBytes();

    /**
     * <code>double amout = 3;</code>
     * @return The amout.
     */
    double getAmout();

    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    double getResult();
  }
  /**
   * Protobuf type {@code ConvertCurrentResponse}
   */
  public  static final class ConvertCurrentResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ConvertCurrentResponse)
      ConvertCurrentResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConvertCurrentResponse.newBuilder() to construct.
    private ConvertCurrentResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConvertCurrentResponse() {
      currentFrom_ = "";
      currentTo_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ConvertCurrentResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConvertCurrentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              currentFrom_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              currentTo_ = s;
              break;
            }
            case 25: {

              amout_ = input.readDouble();
              break;
            }
            case 33: {

              result_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.example.stub.Bank.internal_static_ConvertCurrentResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.example.stub.Bank.internal_static_ConvertCurrentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.example.stub.Bank.ConvertCurrentResponse.class, org.example.stub.Bank.ConvertCurrentResponse.Builder.class);
    }

    public static final int CURRENTFROM_FIELD_NUMBER = 1;
    private volatile java.lang.Object currentFrom_;
    /**
     * <code>string currentFrom = 1;</code>
     * @return The currentFrom.
     */
    public java.lang.String getCurrentFrom() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentFrom_ = s;
        return s;
      }
    }
    /**
     * <code>string currentFrom = 1;</code>
     * @return The bytes for currentFrom.
     */
    public com.google.protobuf.ByteString
        getCurrentFromBytes() {
      java.lang.Object ref = currentFrom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentFrom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CURRENTTO_FIELD_NUMBER = 2;
    private volatile java.lang.Object currentTo_;
    /**
     * <code>string currentTo = 2;</code>
     * @return The currentTo.
     */
    public java.lang.String getCurrentTo() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        currentTo_ = s;
        return s;
      }
    }
    /**
     * <code>string currentTo = 2;</code>
     * @return The bytes for currentTo.
     */
    public com.google.protobuf.ByteString
        getCurrentToBytes() {
      java.lang.Object ref = currentTo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        currentTo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AMOUT_FIELD_NUMBER = 3;
    private double amout_;
    /**
     * <code>double amout = 3;</code>
     * @return The amout.
     */
    public double getAmout() {
      return amout_;
    }

    public static final int RESULT_FIELD_NUMBER = 4;
    private double result_;
    /**
     * <code>double result = 4;</code>
     * @return The result.
     */
    public double getResult() {
      return result_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getCurrentFromBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, currentTo_);
      }
      if (amout_ != 0D) {
        output.writeDouble(3, amout_);
      }
      if (result_ != 0D) {
        output.writeDouble(4, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getCurrentFromBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, currentFrom_);
      }
      if (!getCurrentToBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, currentTo_);
      }
      if (amout_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, amout_);
      }
      if (result_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.example.stub.Bank.ConvertCurrentResponse)) {
        return super.equals(obj);
      }
      org.example.stub.Bank.ConvertCurrentResponse other = (org.example.stub.Bank.ConvertCurrentResponse) obj;

      if (!getCurrentFrom()
          .equals(other.getCurrentFrom())) return false;
      if (!getCurrentTo()
          .equals(other.getCurrentTo())) return false;
      if (java.lang.Double.doubleToLongBits(getAmout())
          != java.lang.Double.doubleToLongBits(
              other.getAmout())) return false;
      if (java.lang.Double.doubleToLongBits(getResult())
          != java.lang.Double.doubleToLongBits(
              other.getResult())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CURRENTFROM_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentFrom().hashCode();
      hash = (37 * hash) + CURRENTTO_FIELD_NUMBER;
      hash = (53 * hash) + getCurrentTo().hashCode();
      hash = (37 * hash) + AMOUT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getAmout()));
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getResult()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.example.stub.Bank.ConvertCurrentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.example.stub.Bank.ConvertCurrentResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ConvertCurrentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ConvertCurrentResponse)
        org.example.stub.Bank.ConvertCurrentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.example.stub.Bank.internal_static_ConvertCurrentResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.example.stub.Bank.internal_static_ConvertCurrentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.example.stub.Bank.ConvertCurrentResponse.class, org.example.stub.Bank.ConvertCurrentResponse.Builder.class);
      }

      // Construct using org.example.stub.Bank.ConvertCurrentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        currentFrom_ = "";

        currentTo_ = "";

        amout_ = 0D;

        result_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.example.stub.Bank.internal_static_ConvertCurrentResponse_descriptor;
      }

      @java.lang.Override
      public org.example.stub.Bank.ConvertCurrentResponse getDefaultInstanceForType() {
        return org.example.stub.Bank.ConvertCurrentResponse.getDefaultInstance();
      }

      @java.lang.Override
      public org.example.stub.Bank.ConvertCurrentResponse build() {
        org.example.stub.Bank.ConvertCurrentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.example.stub.Bank.ConvertCurrentResponse buildPartial() {
        org.example.stub.Bank.ConvertCurrentResponse result = new org.example.stub.Bank.ConvertCurrentResponse(this);
        result.currentFrom_ = currentFrom_;
        result.currentTo_ = currentTo_;
        result.amout_ = amout_;
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.example.stub.Bank.ConvertCurrentResponse) {
          return mergeFrom((org.example.stub.Bank.ConvertCurrentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.example.stub.Bank.ConvertCurrentResponse other) {
        if (other == org.example.stub.Bank.ConvertCurrentResponse.getDefaultInstance()) return this;
        if (!other.getCurrentFrom().isEmpty()) {
          currentFrom_ = other.currentFrom_;
          onChanged();
        }
        if (!other.getCurrentTo().isEmpty()) {
          currentTo_ = other.currentTo_;
          onChanged();
        }
        if (other.getAmout() != 0D) {
          setAmout(other.getAmout());
        }
        if (other.getResult() != 0D) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.example.stub.Bank.ConvertCurrentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.example.stub.Bank.ConvertCurrentResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object currentFrom_ = "";
      /**
       * <code>string currentFrom = 1;</code>
       * @return The currentFrom.
       */
      public java.lang.String getCurrentFrom() {
        java.lang.Object ref = currentFrom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentFrom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return The bytes for currentFrom.
       */
      public com.google.protobuf.ByteString
          getCurrentFromBytes() {
        java.lang.Object ref = currentFrom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentFrom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFrom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentFrom() {
        
        currentFrom_ = getDefaultInstance().getCurrentFrom();
        onChanged();
        return this;
      }
      /**
       * <code>string currentFrom = 1;</code>
       * @param value The bytes for currentFrom to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentFromBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentFrom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object currentTo_ = "";
      /**
       * <code>string currentTo = 2;</code>
       * @return The currentTo.
       */
      public java.lang.String getCurrentTo() {
        java.lang.Object ref = currentTo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          currentTo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return The bytes for currentTo.
       */
      public com.google.protobuf.ByteString
          getCurrentToBytes() {
        java.lang.Object ref = currentTo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          currentTo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentTo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        currentTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCurrentTo() {
        
        currentTo_ = getDefaultInstance().getCurrentTo();
        onChanged();
        return this;
      }
      /**
       * <code>string currentTo = 2;</code>
       * @param value The bytes for currentTo to set.
       * @return This builder for chaining.
       */
      public Builder setCurrentToBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        currentTo_ = value;
        onChanged();
        return this;
      }

      private double amout_ ;
      /**
       * <code>double amout = 3;</code>
       * @return The amout.
       */
      public double getAmout() {
        return amout_;
      }
      /**
       * <code>double amout = 3;</code>
       * @param value The amout to set.
       * @return This builder for chaining.
       */
      public Builder setAmout(double value) {
        
        amout_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double amout = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearAmout() {
        
        amout_ = 0D;
        onChanged();
        return this;
      }

      private double result_ ;
      /**
       * <code>double result = 4;</code>
       * @return The result.
       */
      public double getResult() {
        return result_;
      }
      /**
       * <code>double result = 4;</code>
       * @param value The result to set.
       * @return This builder for chaining.
       */
      public Builder setResult(double value) {
        
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double result = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearResult() {
        
        result_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ConvertCurrentResponse)
    }

    // @@protoc_insertion_point(class_scope:ConvertCurrentResponse)
    private static final org.example.stub.Bank.ConvertCurrentResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.example.stub.Bank.ConvertCurrentResponse();
    }

    public static org.example.stub.Bank.ConvertCurrentResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConvertCurrentResponse>
        PARSER = new com.google.protobuf.AbstractParser<ConvertCurrentResponse>() {
      @java.lang.Override
      public ConvertCurrentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConvertCurrentResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConvertCurrentResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConvertCurrentResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.example.stub.Bank.ConvertCurrentResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertCurrentRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertCurrentRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ConvertCurrentResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ConvertCurrentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbank.proto\"N\n\025ConvertCurrentRequest\022\023\n" +
      "\013currentFrom\030\001 \001(\t\022\021\n\tcurrentTo\030\002 \001(\t\022\r\n" +
      "\005amout\030\003 \001(\001\"_\n\026ConvertCurrentResponse\022\023" +
      "\n\013currentFrom\030\001 \001(\t\022\021\n\tcurrentTo\030\002 \001(\t\022\r" +
      "\n\005amout\030\003 \001(\001\022\016\n\006result\030\004 \001(\0012\227\002\n\rBanque" +
      "Service\022:\n\007convert\022\026.ConvertCurrentReque" +
      "st\032\027.ConvertCurrentResponse\022E\n\020getCurren" +
      "tStream\022\026.ConvertCurrentRequest\032\027.Conver" +
      "tCurrentResponse0\001\022B\n\rperformStream\022\026.Co" +
      "nvertCurrentRequest\032\027.ConvertCurrentResp" +
      "onse(\001\022?\n\nfullStream\022\026.ConvertCurrentReq" +
      "uest\032\027.ConvertCurrentResponse(\001B\022\n\020org.e" +
      "xample.stubb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ConvertCurrentRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ConvertCurrentRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertCurrentRequest_descriptor,
        new java.lang.String[] { "CurrentFrom", "CurrentTo", "Amout", });
    internal_static_ConvertCurrentResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_ConvertCurrentResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ConvertCurrentResponse_descriptor,
        new java.lang.String[] { "CurrentFrom", "CurrentTo", "Amout", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
